using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using Sirenix.OdinInspector;

public enum NodeType
{
    Minor,
    Notable,
    Keystone
}

[CreateAssetMenu(menuName = "Skill Tree/Node")]
public class Node : ScriptableObject
{
    public string Name;
    public Sprite icon;
    public Vector2 coordinates;
    public NodeType nodeType;
    public bool isStartingNode = false;
    public List<PowerUp> powerUps = new List<PowerUp>();

    [System.Serializable]
    public class PowerUp
    {
        public string Description;
        public Stat Stat;
        public float value;

        [Button]
        public void AutoGenerateDescription()
        {
            string statStr = Stat.ToString();

            if (statStr.Contains("Percent"))
            {
                statStr = statStr.Replace("Percent", "% increased ");
                Description = value + statStr;
            }
            else if(statStr.Contains("Flat"))
            {
                statStr = statStr.Replace("Flat", " to ");
                Description = value + statStr;
            }
        }

        public void ApplyPowerUp()
        {
            Player.instance.AddStat(Stat, value);
        }

        public void UnapplyPowerUp()
        {
            Player.instance.AddStat(Stat, -value);
        }
    }

    [ReadOnly] public List<Node> connectedNodes;

    public bool IsActive
    {
        get
        {
            return isActive;
        }
        set
        {
            if(value != isActive)
            {
                isActive = value;
                ApplyPowerUps(value);
                OnActiveChanged?.Invoke(value);
                SkillTreeManager.instance.RefreshSkillTree();
            }
        }
    }

    public System.Action<bool> OnActiveChanged;

    [ReadOnly, SerializeField] bool isActive;

    [Header("Connect Nodes")]
    [SerializeField] Node NodeToConnect;

    public bool CanBeToggledOn()
    {
        if (IsActive)
            return false;

        if (Player.instance.skillPoints <= 0)
            return false;

        if (isStartingNode)
            return true;

        for (int i = 0; i < connectedNodes.Count; i++)
        {
            if (connectedNodes[i].isActive)
                return true;
        }

        return false;
    }

    public bool CanBeToggledOff()
    {
        if (!IsActive)
            return false;

        //add active connected nodes to a list
        List<Node> activeConnectedNodes = new List<Node>();

        for (int i = 0; i < connectedNodes.Count; i++)
        {
            if (connectedNodes[i].isActive)
                activeConnectedNodes.Add(connectedNodes[i]);
        }

        //loop through all active connected nodes to see if they will still be connected to the start
        for (int i = activeConnectedNodes.Count - 1; i >= 0; i--)
        {
            bool didTurnOff = false;

            List<Node> checkedNodes = new List<Node>();
            List<Node> nodesToCheck = new List<Node>();

            nodesToCheck.Add(activeConnectedNodes[i]);

            while (nodesToCheck.Count > 0)
            {
                Node nodeBeingChecked = nodesToCheck[0];

                nodesToCheck.Remove(nodeBeingChecked);
                checkedNodes.Add(nodeBeingChecked);

                if (nodeBeingChecked.isStartingNode && nodeBeingChecked.isActive)
                {
                    activeConnectedNodes.Remove(activeConnectedNodes[i]);
                    didTurnOff = true;

                    if (activeConnectedNodes.Count == 0)
                        return true;

                    break;
                }

                for (int j = 0; j < nodeBeingChecked.connectedNodes.Count; j++)
                {
                    if (nodeBeingChecked.connectedNodes[j] == this)
                        continue;
                    if (!nodeBeingChecked.connectedNodes[j].isActive)
                        continue;
                    if (checkedNodes.Contains(nodeBeingChecked.connectedNodes[j]))
                        continue;
                    if (nodesToCheck.Contains(nodeBeingChecked.connectedNodes[j]))
                        continue;

                    nodesToCheck.Add(nodeBeingChecked.connectedNodes[j]);
                }
            }

            if (!didTurnOff)
                return false;
        }

        if (activeConnectedNodes.Count == 0)
            return true;
        else
            return false;
    }  

    public void ToggleNode()
    {
        if (CanBeToggledOn())
        {
            Player.instance.skillPoints--;
            IsActive = true;
        }
        else if (CanBeToggledOff())
        {
            Player.instance.skillPoints++;
            IsActive = false;
        }
    }

    public void ApplyPowerUps(bool toggle)
    {
        if (toggle)
        {
            for (int i = 0; i < powerUps.Count; i++)
            {
                powerUps[i].ApplyPowerUp();
            }
        }
        else
        {
            for (int i = 0; i < powerUps.Count; i++)
            {
                powerUps[i].UnapplyPowerUp();
            }
        }

        GameManager.Save();
    }

    [Button]
    public void ConnectOrRemoveNode()
    {
        if(connectedNodes.Contains(NodeToConnect))
        {
            connectedNodes.Remove(NodeToConnect);
            NodeToConnect.connectedNodes.Remove(this);
        }
        else
        {
            connectedNodes.Add(NodeToConnect);
            NodeToConnect.connectedNodes.Add(this);
        }

        NodeToConnect = null;
    }
}
